import type { Paper, Summary } from "./index";

export const papers: Paper[] = [
  {
    id: "p1",
    title: "Attention Is All You Need",
    authors: ["Vaswani, A.", "Shazeer, N.", "Parmar, N."],
    year: 2017,
    venue: "NeurIPS",
    tags: ["Transformer", "NLP", "Attention"],
    abstract: "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks...",
    pdfUrl: "https://arxiv.org/pdf/1706.03762",
    imageUrl: "/mockup_thumb.jpg",
    metrics: { trendingScore: 95, recencyScore: 60, citations: 85000 },
  },
  {
    id: "p2",
    title: "BERT: Pre-training of Deep Bidirectional Transformers",
    authors: ["Devlin, J.", "Chang, M.", "Lee, K."],
    year: 2019,
    venue: "NAACL",
    tags: ["NLP", "Transformer", "Pre-training"],
    abstract: "We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers...",
    pdfUrl: "https://arxiv.org/pdf/1810.04805",
    imageUrl: "/mockup_thumb.jpg",
    metrics: { trendingScore: 88, recencyScore: 65, citations: 65000 },
  },
  {
    id: "p3",
    title: "Denoising Diffusion Probabilistic Models",
    authors: ["Ho, J.", "Jain, A.", "Abbeel, P."],
    year: 2020,
    venue: "NeurIPS",
    tags: ["Diffusion", "Generative", "Vision"],
    abstract: "We present high quality image synthesis results using diffusion probabilistic models...",
    pdfUrl: "https://arxiv.org/pdf/2006.11239",
    imageUrl: "/mockup_thumb.jpg",
    metrics: { trendingScore: 92, recencyScore: 75, citations: 12000 },
  },
  {
    id: "p4",
    title: "Proximal Policy Optimization Algorithms",
    authors: ["Schulman, J.", "Wolski, F.", "Dhariwal, P."],
    year: 2017,
    venue: "arXiv",
    tags: ["RL", "Policy Gradient", "Optimization"],
    abstract: "We propose a new family of policy gradient methods for reinforcement learning...",
    pdfUrl: "https://arxiv.org/pdf/1707.06347",
    imageUrl: "/mockup_thumb.jpg",
    metrics: { trendingScore: 85, recencyScore: 55, citations: 18000 },
  },
  {
    id: "p5",
    title: "Vision Transformer (ViT)",
    authors: ["Dosovitskiy, A.", "Beyer, L.", "Kolesnikov, A."],
    year: 2021,
    venue: "ICLR",
    tags: ["Vision", "Transformer", "Image Classification"],
    abstract: "While the Transformer architecture has become the de-facto standard for NLP tasks, its applications to computer vision remain limited...",
    pdfUrl: "https://arxiv.org/pdf/2010.11929",
    imageUrl: "/mockup_thumb.jpg",
    metrics: { trendingScore: 90, recencyScore: 80, citations: 22000 },
  },
  {
    id: "p6",
    title: "GPT-4 Technical Report",
    authors: ["OpenAI"],
    year: 2023,
    venue: "arXiv",
    tags: ["LLM", "Multimodal", "Scaling"],
    abstract: "We report the development of GPT-4, a large-scale multimodal model which can accept image and text inputs...",
    pdfUrl: "https://arxiv.org/pdf/2303.08774",
    imageUrl: "/mockup_thumb.jpg",
    metrics: { trendingScore: 98, recencyScore: 95, citations: 8000 },
  },
  {
    id: "p7",
    title: "Reinforcement Learning from Human Feedback",
    authors: ["Christiano, P.", "Leike, J.", "Brown, T."],
    year: 2017,
    venue: "NeurIPS",
    tags: ["RL", "RLHF", "Human Feedback"],
    abstract: "For sophisticated reinforcement learning systems to interact usefully with real-world environments...",
    pdfUrl: "https://arxiv.org/pdf/1706.03741",
    imageUrl: "/mockup_thumb.jpg",
    metrics: { trendingScore: 94, recencyScore: 70, citations: 5000 },
  },
  {
    id: "p8",
    title: "Stable Diffusion",
    authors: ["Rombach, R.", "Blattmann, A.", "Lorenz, D."],
    year: 2022,
    venue: "CVPR",
    tags: ["Diffusion", "Vision", "Generative"],
    abstract: "We present high-resolution image synthesis with latent diffusion models...",
    pdfUrl: "https://arxiv.org/pdf/2112.10752",
    imageUrl: "/mockup_thumb.jpg",
    metrics: { trendingScore: 96, recencyScore: 88, citations: 15000 },
  },
  {
    id: "p9",
    title: "Chain-of-Thought Prompting",
    authors: ["Wei, J.", "Wang, X.", "Schuurmans, D."],
    year: 2022,
    venue: "NeurIPS",
    tags: ["LLM", "Prompting", "Reasoning"],
    abstract: "We explore how generating a chain of thought -- a series of intermediate reasoning steps...",
    pdfUrl: "https://arxiv.org/pdf/2201.11903",
    imageUrl: "/mockup_thumb.jpg",
    metrics: { trendingScore: 91, recencyScore: 85, citations: 6000 },
  },
  {
    id: "p10",
    title: "ResNet: Deep Residual Learning",
    authors: ["He, K.", "Zhang, X.", "Ren, S."],
    year: 2016,
    venue: "CVPR",
    tags: ["Vision", "CNN", "Deep Learning"],
    abstract: "Deeper neural networks are more difficult to train. We present a residual learning framework...",
    pdfUrl: "https://arxiv.org/pdf/1512.03385",
    imageUrl: "/mockup_thumb.jpg",
    metrics: { trendingScore: 75, recencyScore: 40, citations: 150000 },
  },
  {
    id: "p11",
    title: "Constitutional AI",
    authors: ["Bai, Y.", "Kadavath, S.", "Kundu, S."],
    year: 2022,
    venue: "arXiv",
    tags: ["LLM", "Safety", "Alignment"],
    abstract: "We discuss a method we call Constitutional AI (CAI) for training harmless AI assistants...",
    pdfUrl: "https://arxiv.org/pdf/2212.08073",
    imageUrl: "/mockup_thumb.jpg",
    metrics: { trendingScore: 89, recencyScore: 90, citations: 1500 },
  },
  {
    id: "p12",
    title: "Segment Anything (SAM)",
    authors: ["Kirillov, A.", "Mintun, E.", "Ravi, N."],
    year: 2023,
    venue: "ICCV",
    tags: ["Vision", "Segmentation", "Foundation Model"],
    abstract: "We introduce the Segment Anything project: a new task, model, and dataset for image segmentation...",
    pdfUrl: "https://arxiv.org/pdf/2304.02643",
    imageUrl: "/mockup_thumb.jpg",
    metrics: { trendingScore: 97, recencyScore: 92, citations: 4000 },
  },
];

// summaries 배열 삭제됨 -- 이제 useSummary 훅으로 백엔드 API에서 가져옴



export const allTags = [
  "Transformer", "NLP", "Vision", "RL", "Diffusion",
  "LLM", "Generative", "Attention", "CNN", "RLHF",
  "Multimodal", "Prompting", "Safety", "Segmentation"
];
